name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytest
  - numpy
  - pip
  - pip:
      - pylint
      - plotly
      - plot
      - streamlit
      - coverage
      - -r requirements.txt
